# Generated by Django 2.1.5 on 2019-01-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to=None),
        ),
    ]
